apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test-oct4-01 
  janus-idp.io/tekton: test-oct4-01
  backstage.io/kubernetes-id: test-oct4-01
  backstage.io/kubernetes-namespace: test-rhdh-app 
  app.kubernetes.io/part-of: test-oct4-01
resources: 
- application-dev.yaml